#version: "3.8"

#services:
  #db:
    #image: mysql:8.0
    #container_name: mysql-db
    #environment:
      #MYSQL_ROOT_PASSWORD: root
      #MYSQL_DATABASE: job_portal
      #MYSQL_USER: jobuser
      #MYSQL_PASSWORD: jobpass
    #ports:
      #- "3306:3306"
    #healthcheck:
      #test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      #interval: 10s
      #timeout: 5s
      #retries: 5

  #app:
    #build: .
    #container_name: job-portal-app
    #ports:
      #- "8085:8085"
    #environment:
      #PORT: 8085
      #SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/job_portal
      #SPRING_DATASOURCE_USERNAME: jobuser
      #SPRING_DATASOURCE_PASSWORD: jobpass
    #depends_on:
      #db:
        #condition: service_healthy

        app:
  build: .
  container_name: job-portal-app
  ports:
    - "8085:8085"
  environment:
    SPRING_APPLICATION_JSON: '{"server":{"port":8085}}'
    SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/job_portal
    SPRING_DATASOURCE_USERNAME: jobuser
    SPRING_DATASOURCE_PASSWORD: jobpass
  depends_on:
    db:
      condition: service_healthy

